use crate::models::CivInfo;

pub const HEADER_LENGTH: usize = 10;

pub fn civ_info_for_replay_id(civ_id: i32) -> Option<CivInfo> {
    match civ_id {
        1 => Some(info(
            "Spanish",
            "flag_hc_spanish.png",
            "Flag_Spanish.png",
            "postgame_flag_spanish.png",
            1,
            "homecityspanish",
        )),
        2 => Some(info(
            "British",
            "flag_hc_british.png",
            "Flag_British.png",
            "postgame_flag_british.png",
            2,
            "homecitybritish",
        )),
        3 => Some(info(
            "French",
            "flag_hc_french.png",
            "Flag_French.png",
            "postgame_flag_french.png",
            3,
            "homecityfrench",
        )),
        4 => Some(info(
            "Portuguese",
            "flag_hc_portuguese.png",
            "Flag_Portuguese.png",
            "postgame_flag_portuguese.png",
            4,
            "homecityportuguese",
        )),
        5 => Some(info(
            "Dutch",
            "flag_hc_dutch.png",
            "Flag_Dutch.png",
            "postgame_flag_dutch.png",
            5,
            "homecitydutch",
        )),
        6 => Some(info(
            "Russians",
            "flag_hc_russian.png",
            "Flag_Russian.png",
            "postgame_flag_russian.png",
            6,
            "homecityrussians",
        )),
        7 => Some(info(
            "Germans",
            "flag_hc_german.png",
            "Flag_German.png",
            "postgame_flag_german.png",
            7,
            "homecitygerman",
        )),
        8 => Some(info(
            "Ottoman",
            "flag_hc_ottoman.png",
            "Flag_Ottoman.png",
            "postgame_flag_ottoman.png",
            8,
            "homecityottomans",
        )),
        15 => Some(info(
            "Haudenosaunee",
            "flag_hc_iroquois.png",
            "Flag_Iroquois.png",
            "postgame_flag_iroquois.png",
            9,
            "homecityxpiroquois",
        )),
        16 => Some(info(
            "Lakota",
            "flag_hc_sioux.png",
            "Flag_Sioux.png",
            "postgame_flag_sioux.png",
            10,
            "homecityxpsioux",
        )),
        17 => Some(info(
            "Aztecs",
            "flag_hc_aztec.png",
            "Flag_Aztec.png",
            "postgame_flag_aztec.png",
            11,
            "homecityxpaztec",
        )),
        19 => Some(info(
            "Japanese",
            "flag_hc_japanese.png",
            "Flag_Japanese.png",
            "postgame_flag_japanese.png",
            13,
            "homecityjapanese",
        )),
        20 => Some(info(
            "Chinese",
            "flag_hc_chinese.png",
            "Flag_Chinese.png",
            "postgame_flag_chinese.png",
            12,
            "homecitychinese",
        )),
        21 => Some(info(
            "Indians",
            "flag_hc_indian.png",
            "Flag_Indian.png",
            "postgame_flag_indian.png",
            14,
            "homecityindians",
        )),
        27 => Some(info(
            "Inca",
            "flag_hc_inca.png",
            "Flag_Incan.png",
            "postgame_flag_inca.png",
            15,
            "homecitydeinca",
        )),
        28 => Some(info(
            "Swedes",
            "flag_hc_swedish.png",
            "Flag_Swedish.png",
            "postgame_flag_swedish.png",
            16,
            "homecityswedish",
        )),
        38 => Some(info(
            "United States",
            "flag_hc_american.png",
            "Flag_American.png",
            "postgame_flag_american.png",
            17,
            "homecityamericans",
        )),
        39 => Some(info(
            "Ethiopians",
            "flag_hc_ethiopian.png",
            "Flag_Ethiopian.png",
            "postgame_flag_ethiopian.png",
            18,
            "homecityethiopians",
        )),
        40 => Some(info(
            "Hausa",
            "flag_hc_hausa.png",
            "Flag_Hausa.png",
            "postgame_flag_hausa.png",
            19,
            "homecityhausa",
        )),
        42 => Some(info(
            "Mexicans",
            "flag_hc_mexican.png",
            "Flag_Mexican.png",
            "postgame_flag_mexican.png",
            20,
            "homecitymexicans",
        )),
        44 => Some(info(
            "Italians",
            "flag_hc_italian.png",
            "Flag_Italian.png",
            "postgame_flag_italian.png",
            21,
            "homecityitalians",
        )),
        45 => Some(info(
            "Maltese",
            "flag_hc_maltese.png",
            "Flag_Maltese.png",
            "postgame_flag_maltese.png",
            22,
            "homecitymaltese",
        )),
        _ => None,
    }
}

fn info(
    name: &'static str,
    url_circle: &'static str,
    url_rectanle: &'static str,
    url_left: &'static str,
    id_civ: i32,
    homecity_json: &'static str,
) -> CivInfo {
    CivInfo {
        name,
        url_circle,
        url_rectanle,
        url_left,
        id_civ,
        homecity_json,
    }
}
